#'''Computational resource config.'''#


count_reads_mem_mb: 100000


# --- assembly --- #

assembly_threads: 30
assembly_mem_mb:  200000

# --- polishing --- #

polishing_threads: 30
bowtie2_threads: 30

# --- quast --- #

quast_threads: 30
quast_mem_mb:  200000
